# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zeroward < Formula
  desc ""
  homepage "https://github.com/Abdiooa/homebrew-tools"
  version "1.0.39"
  license "Apache"

  on_macos do
    url "https://github.com/Abdiooa/zeroward/releases/download/v1.0.39/zeroward_1.0.39_darwin-all.tar.gz"
    sha256 "27668f9696503a202d54bda7ce44cef80f3d9cca94064c2502e728af33af303e"

    def install
      bin.install "zeroward"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abdiooa/zeroward/releases/download/v1.0.39/zeroward_1.0.39_linux-arm64.tar.gz"
      sha256 "7cacd62ca74e1484649c5c29eda559b29e6ecb082a855ef0bd52c30b95b994dd"

      def install
        bin.install "zeroward"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Abdiooa/zeroward/releases/download/v1.0.39/zeroward_1.0.39_linux-amd64.tar.gz"
      sha256 "fdbf1d6d8821ab50a43fa7694ad4aefe5997f27d349c92135c177bbb7d5cbd97"

      def install
        bin.install "zeroward"
      end
    end
  end
end
